### ISSUE TITLE
canal da SIC

### ISSUE THREAD

**Issue by miraldo** [adrianoafonso/myIPTVchannels#4]
Boa tarde, o canal da SIC, não funciona

**Comment by miraldo** [comment]
http://213.13.26.11:1935/live/sic/livestream.m3u8

Posso alterar?

**Comment by learisa** [comment]
Sim numa boa pois tem muito boa qualidade parabens pela pesquisa
Em 20/10/2015 23:12, "miraldo" <notifications@github.com> escreveu:

**Comment by madman227** [comment]
Ja existe na listagem da smart-tv há muito tempo...

#EXTINF:-1 tvg-id="sic.pt" tvg-logo="https://raw.githubusercontent.com/adrianoafonso/myIPTVchannels/master/Logos/SIC.png",SIC
http://213.13.26.11:1935/live/sic/cookiemonster.m3u8

**Comment by tiagosilva89** [comment]
Boas. Peço desculpa estou com um problema é não sei como resolver..
Eu ainda sou novo nas listas iptv não sei bem como meter estes canais todos no kodi. 
Alguém me pode dar uma mão 
Obrigadinho

**Comment by sheikr** [comment]
@tiagosilva89 Vê a secção tutorials no site kodiportugal.com ou pergunta no grupo do Facebook. Em relação a este issue, já está corrigido e pode ser fechado.
